language: java

env:
  global:
    - SONATYPE_USERNAME=solcyr
    - secure: "YV3Ie+5Xhzl4mheZfbnOzClBcVnGI4u5wd8fyQBMfDVJXe5RMBR/MC1L11Ne5K71L885Vf0RdaeTvyujTzorE99N0zgs+H9ydTLdYCiXk6BRxvDwC6toBnOtg7Y7AdXT1Xc83cbHhe0DCYWp1PWH6ziAc/LCg33AuQp/FeoWsW1tb5gHosSCihMrcWspAX/bF350JIFQawD3S4fUJQyNC3+2alEYoioqLuMXLK89lX1VJ4XBi8FS5EkmPXXskUy8vtDNruUyhitrcH0N3g3lapsYb+ll5rAguHKkXIyE7cZNkLA2LtO+M1GmXonAhhA+RpXPwd+dOP8VPJ25TkdEX2+Q7H1aW4dqq7Temp7qQSQrXxUGmYIs/wvGXuChBhvyLQwNUf9G3xxn/HYxIR1Qc0FHU5Smkiu2wEIttLcmmva8meGVB9cPT6R0tjzvn0nR3SV9ibx2DBfvuebIRAzDTXgZPDynhsEdK8pRoGRjlHD0ATHzL5UuKHvhWWht+iXYHL0ilMSVbC39DEbggrD1KcCFJBdi2qg1yRFGNMYAgFanQx/oBA9r/rfRAVRf2wh2axZzMH498d4qbrCFsi+YNFkoXM6xbfd3Fx4QDxG/OwwrGGnjKloRW6+2h2d0VEtVX1kgA7puO9tqQqABuZb428umjfAzMvKD1QCX/nhSEsM="

services:
- docker
cache:
  directories:
  - "$HOME/.cache"

before_script:
  - unset _JAVA_OPTIONS

install: true
script: mvn -Dbuild.travis=true install 

deploy:
  provider: script
  script: mvn -DskipTests=true deploy --settings .travis.settings.xml
  skip_cleanup: true
  #on:
  #  tags: true
